version: "3.8"
services:
    web:
      container_name: web
      build: .
      ports:
          - "8080:80"
      depends_on:
        - db
      restart: on-failure
    db:
      container_name: db
      image: "mcr.microsoft.com/mssql/server:2019-latest"
      ports:
        - "1433:1433"
      environment:
        SA_PASSWORD: "Strongpassword1!"
        ACCEPT_EULA: "Y"